### ISSUE TITLE
/accounts/balance hangs

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-rosetta-gateway#347]
probably happens when we try to populate the detailed delegation records for our custom metadata.

we'll have to remove this because we don't currently have a way to retrieve this other than to brute-force loop over all delegations

cross reference #61 , #62

**Comment by pro-wh** [comment]
From #377:

> When attempting to use the balance endpoint to get the escrow balance the server hangs:
> 
> ```
> curl --location --request POST '<ROSETTA_URL>/account/balance' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "network_identifier": {"blockchain":"Oasis","network":"b11b369e0da5bb230b220127f5e7b242d385ef8c6f54906243f30af63c815535"},
>     "account_identifier": {
>         "address":  "oasis1qr0j8kqnejng4rutkw7elsuweu77l06pjugaxuqx",
>         "sub_account": {
>             "address": "escrow"
>         }
>     }
> }
> '
> ```
> 
> Server hangs indefinitely on this request and any request with the escrow sub_account.

And thanks for posting a simple command to test with.

@protango Could I have you try on this branch? https://github.com/oasisprotocol/oasis-rosetta-gateway/tree/pro-wh/feature/delegations

**Comment by yerycs** [comment]
What is the alternative way to get escrow balance since it is still open issue and not resolved yet?

**Comment by heindrick17** [comment]
Hello @pro-wh I tried your comment by patching out code lines,
I got response. But I got 0 amount for all balance even active balance. What do you think?

**Comment by pro-wh** [comment]
> But I got 0 amount for all balance even active balance. What do you think?

can you open a new issue with some more information about this? the gateway uses the balance directly from the oasis-node. can you try getting the account info with the cli https://github.com/oasisprotocol/cli/ connected to that node?

**Comment by heindrick17** [comment]
When I try without `sub_account`, it is showing correct active balance. So, I don't think it is node issue.
```
{
      "block_identifier": {
        "index": 13422205,
        "hash": "edca42fa854d1e55c8d61b941860140315bcd6494e430a6aaf3159d0de14b2b0"
      },
      "balances": [
        {
          "value": "0",
          "currency": {
            "symbol": "ROSE",
            "decimals": 9
          }
        }
      ],
      "metadata": {
        "active_balance": "0",
        "active_shares": "0",
        "debonding_balance": "0",
        "debonding_shares": "0",
        "nonce": 128
      }
    }
```
It is balance response when adding `sub_account` after patching out code lines

**Comment by pro-wh** [comment]
that means no ROSE is delegated _to_ that address. you need to put in the address of, for example, a validator to see the total ROSE delegated to it.

**Comment by heindrick17** [comment]
Ah, Then how can I get delegator's escrow balance?

**Comment by pro-wh** [comment]
unfortunately there's no fast way to do it in the 22.2.x oasis-node. there's only that slow piece of code that was timing out for you

**Comment by pro-wh** [comment]
we've resolved this in oasis-core
